set nocompatible
filetype off

"Runtime Path Adds
set rtp+=~/.vim/bundle/Vundle.vim
set rtp+=~/.vim/colors/*.vim

"Swap Files Location
set directory=~/.vim/swapfiles//

call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-airline/vim-airline'
Plugin 'preservim/nerdtree'
Plugin 'leafgarland/typescript-vim'
Plugin 'morhetz/gruvbox'
"Language Extensions
Plugin 'PProvost/vim-ps1'
Plugin 'curist/vim-angular-template'
Plugin 'pangloss/vim-javascript'
Plugin 'ekalinin/Dockerfile.vim'
Plugin 'stephpy/vim-yaml'

call vundle#end()
filetype plugin indent on
filetype on
syntax on

"Color Settings
colorscheme gruvbox
set background=dark

"Spacing and Tabs
set tabstop=2
set softtabstop=2
set expandtab
set shiftwidth=0


"UI Config
set relativenumber
set showcmd
set cursorline
set lazyredraw
set showmatch
set number
set colorcolumn=100
filetype indent on


"Searching
set incsearch
set hlsearch
set ignorecase
set path+=**
set wildmenu

"Folding
set foldenable
set foldlevelstart=10
set foldnestmax=10
nnoremap <space> za
set foldmethod=indent

"Movement
nnoremap j gj
nnoremap k gk

"Non-Movemnt Bindings
no <up> ddkP
no <down> ddp
no <left> <Nop>
no <right> <Nop>

ino <up> <Nop>
ino <down> <Nop>
ino <left> <Nop>
ino <right> <Nop>

vno <up> <Nop>
vno <down> <Nop>
vno <left> <Nop>
vno <right> <Nop>

"Center on move
nmap G Gzz
nmap gg ggzz
nmap n nzzLzz
nmap N NzzLzz
nmap } }zz
nmap { {zz

"Leader Shortcuts
let mapleader = " "

nnoremap <leader>h :wincmd h<CR>
nnoremap <leader>j :wincmd j<CR>
nnoremap <leader>k :wincmd k<CR>
nnoremap <leader>l :wincmd l<CR>
nnoremap <leader>nt :NERDTree<CR>

"Open file quickly
nnoremap <leader>f :find<Space>

nnoremap <leader>+ :verticle resize +5<CR>
nnoremap <leader>- :verticle resize -5<CR>
"Ctrl_P
"Backups

set undofile
set undodir=~/.vim/undodir
set noswapfile
set nobackup

